routes/web.php
<?php

use App\Http\Controllers\LoadController;
use App\Http\Controllers\PointController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [LoadController::class, 'showExchange']);

Route::resource('/loads', LoadController::class)->except(['create']);
Route::resource('/points', PointController::class);

app/Models/Load.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Load extends Model
{
    use HasFactory;

    /**
     * @var $fillable string[]
     */
    protected $fillable = ['name', 'weight'];

    /**
     * @var $casts string[]
     */
    protected $casts = [
        'name' => 'string',
        'weight' => 'integer',
    ];

    /**
     * @var $rules array|string[]
     */
    protected array $rules = [
        'name' => 'required|string',
        'weight' => 'required|integer',
    ];

    public function points(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Point::class);
    }
}

app/Models/Point.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Point extends Model
{
    use HasFactory;

    /**
     * @var $fillable string[]
     */
    protected $fillable = ['name', 'date', 'load_id'];

    /**
     * @var $casts string[]
     */
    protected $casts = [
        'name' => 'string',
        'date' => 'date',
        'load_id' => 'integer',
    ];

    /**
     * @var $rules array|string[]
     */
    protected array $rules = [
        'name' => 'required|string',
        'date' => 'required|date',
        'load_id' => 'required|integer',
    ];

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        static::addGlobalScope(new PointOrderScope());
    }

    /**
     * Relation
     *
     * @return BelongsTo
     */
    public function cargo(): BelongsTo
    {
        return $this->belongsTo(Load::class);
    }


}

app/Models/PointOrderScope.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class PointOrderScope implements \Illuminate\Database\Eloquent\Scope
{

    /**
     * @inheritDoc
     */
    public function apply(Builder $builder, Model $model)
    {
        $builder->orderBy('date', 'asc');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Load;
use App\Http\Requests\StoreLoadRequest;
use App\Http\Requests\UpdateLoadRequest;
use App\Services\LoadPointService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Response;

class LoadController extends Controller
{
    /** Show Home blade
     *
     * @return Factory|View|Application
     */
    protected function showExchange(): Factory|View|Application
    {
        return view('home');
    }

    /**
     * Display a listing of the resource.
     *
     * @param LoadPointService $pointService
     * @return JsonResponse
     */
    public function index(LoadPointService $pointService): JsonResponse
    {
        $loads = $pointService->loadsList();
        return response()->json($loads);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreLoadRequest $request
     * @param LoadPointService $pointService
     * @return JsonResponse
     */
    public function store(StoreLoadRequest $request, LoadPointService $pointService): JsonResponse
    {
        try {
            $newLoad = $pointService->createLoad($request->input('loadName'), $request->input('weight'));
            $pointService->createLoadPoints(
                $newLoad->id,
                $request->input('raceDate'),
                $request->input('pointFrom'),
                $request->input('pointTo'));
            $result = 'ok';
        }catch (\Exception $exception) {
            $result = $exception->getMessage();
        }

        return response()->json($result);
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Load $load
     * @return Response
     */
    public function show(Load $load)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Load $load
     * @return Response
     */
    public function edit(Load $load)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \App\Http\Requests\UpdateLoadRequest $request
     * @param \App\Models\Load $load
     * @return Response
     */
    public function update(UpdateLoadRequest $request, Load $load)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Load $load
     * @return Response
     */
    public function destroy(Load $load)
    {
        //
    }
}

app/Http/Controllers/PointController.php
<?php

namespace App\Http\Controllers;

use App\Models\Point;
use App\Http\Requests\StorePointRequest;
use App\Http\Requests\UpdatePointRequest;

class PointController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePointRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePointRequest $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Point  $point
     * @return \Illuminate\Http\Response
     */
    public function show(Point $point)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Point  $point
     * @return \Illuminate\Http\Response
     */
    public function edit(Point $point)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePointRequest  $request
     * @param  \App\Models\Point  $point
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePointRequest $request, Point $point)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Point  $point
     * @return \Illuminate\Http\Response
     */
    public function destroy(Point $point)
    {
        //
    }
}

resources/views/home.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
<!--main page-->
<div id="exchange">
    <main class="pt-10 pb-20">
        <div class="container mx-auto px-4">
            <h1 class="text-2xl font-bold">Біржа вантажів</h1>
            <div class="flex flex-col pt-4 pb-8 gap-y-2 lg:w-2/3 xl:w-1/2">
                <button class="border-none rounded bg-blue-600 text-white font-bold py-2 px-8 inline-block mr-auto" @click="showModalMethod">
                    Додати
                </button>
                <div class="">Всього: @{{ cargoAmount }} вантажів</div>
                <div class="w-full border divide-y">
                    <div class="grid grid-cols-5 font-bold">
                        <div class="py-1 px-4">Дата</div>
                        <div class="py-1 px-4 col-span-2">Маршрут</div>
                        <div class="py-1 px-4">Вантаж</div>
                        <div class="py-1 px-4">Вага</div>
                    </div>
                    <div class="divide-y flex flex-col" id="tableImitate" v-for="load in cargo">
                            <div class="divide-y border">
                                <div class="w-full grid grid-cols-5">
                                    <div class="py-1 px-4">   {{-- ->format('d.m.Y') --}}
                                        <span v-if="load.date">
                                            @{{ normalDate(load.date) }}</span>
                                        <span v-else>"нема"</span>
                                    </div>
                                    <div class="py-1 px-4 col-span-2">
                                        <span v-if="load.route">@{{ load.route }}</span>
                                        <span v-else>"нема"</span>
                                    </div>
                                    <div class="py-1 px-4">@{{ load.name }}</div>
                                    <div class="py-1 px-4">@{{ load.weight }}</div>
                                </div>
                                {{--                        @endforeach--}}
                        {{--                        <div class="h-80">--}}
                        {{--                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5441169.1233852515!2d26.69303850676986!3d48.248575770282166!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40d1d9c154700e8f%3A0x1068488f64010!2sUkraine!5e0!3m2!1sen!2sru!4v1636544003860!5m2!1sen!2sru" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>--}}
                        {{--                        </div>--}}
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!--TODO Для відображення модалу видалити класс hidden у наступного блоку-->
    <!--modal overlay-->
    <div class="fixed inset-0 flex items-center justify-center" v-if="showModal" style="background: rgba(0, 0, 0, 0.4)">
        <!--    modal body-->
        <div class="bg-white w-1/3 p-5 flex flex-col gap-4 relative">
            <!--        close button-->
            <button class="absolute right-5 top-5 h-4 w-4" @click="showModalMethod()">
                <span class="bg-gray-300 absolute transform rotate-45 block h-0.5 w-4"></span>
                <span class="bg-gray-300 absolute transform -rotate-45 block h-0.5 w-4"></span>
            </button>
            <!--        title-->
            <h2 class="text-xl font-bold">Нове замовлення</h2>
            <!--        form-->
            <form class="flex flex-col gap-y-6" method="post">
                <div class="grid grid-cols-2 gap-4">
                    @csrf
                    <label>
                        <input type="date" name="raceDate" v-model="load.raceDate" required>
                    </label>
                    <label>
                        <input class="border rounded py-2 px-4 w-full" type="text" name="from" placeholder="Звідки" v-model="load.pointFrom" required>
                    </label>
                    <label>
                        <input class="border rounded py-2 px-4 w-full" type="text" name="to" placeholder="Куди" v-model="load.pointTo" required>
                    </label>
                    <label>
                        <input class="border rounded py-2 px-4 w-full" type="text" name="name" placeholder="Назва вантажу" v-model="load.loadName" required>
                    </label>
                    <label>
                        <input class="border rounded py-2 px-4 w-full" type="text" name="weight" placeholder="Вага, кг" v-model="load.weight" required>
                    </label>
                </div>
                <button class="border-none rounded bg-blue-600 text-white font-bold py-2 px-8 inline-block ml-auto" @click.prevent="validateInput">
                    Додати
                </button>
            </form>
        </div>
    </div>
</div>
@routes
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{{asset('js/main.js')}}" defer></script>
<script>
    const queryUrl = "{{asset(route('loads.store'))}}";
</script>
</body>
</html>